title: "Mental Health and Neurological Specialists per 100,000 Inhab"
description: "Longitudinal dataset (2000-2026) on the density of mental health and neurology specialists per 100,000 inhabitants in 16 Ibero-American countries, inc"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/mental-health-and-neurological-specialists-per-100000-inhabitants-in-ibero-ameri"
